### PR TITLE
Task modal

### PR DESCRIPTION
**Pull request by CornFarmerNZ**

### CODE REVIEW

**Review by Hgarnell — COMMENTED** [review]
looks good! I'm happy to take over on working on the CSS so it matches the rest of the site

**Comment by logan-wood** [comment]
i noticed the tasks aren't user specific, is it possible to make them user specific? Other than that, it looks good.

**Comment by CornFarmerNZ** [comment]
> looks good! I'm happy to take over on working on the CSS so it matches the rest of the site

lol please do! kinda gave up towards the end

**Comment by CornFarmerNZ** [comment]
> i noticed the tasks aren't user specific, is it possible to make them user specific? Other than that, it looks good.

I just tested this myself and it seems like switching to another user keeps the tasks of the previous user cached, but if u add a task it will reload the new user's tasks (which will be different). i'll try to see if i can fit a task retriever function somewhere when the application loads

**Pull request merged**
